version: "3.8"

services:
  frontend:
    image: nginx
    volumes:
      - ./frontend_build:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - backend

  postgres:
    image: postgres:13
    restart: always

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      retries: 5
      timeout: 5s

  backend:
    build: ./backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy  # 👈 Wait for PostgreSQL to be ready
    environment:
      DB_HOST: postgres
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
      DB_PORT: 5432
    ports:
      - "8000:8000"

