version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8000:8000"

  frontend:
    image: nginx
    volumes:
      - ./frontend_build:/usr/share/nginx/html
    ports:
      - "80:80"

  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_NAME: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}