version: "3.8"

services:
  frontend:
    image: nginx
    volumes:
      - ./frontend_build:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - backend

  postgres:
    image: postgres:13
    restart: always

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      retries: 5
      timeout: 5s

  backend:
    build:
      context: ./backend  # 👈 Ensure this points to the `backend/` folder
      dockerfile: Dockerfile  
    restart: always
    depends_on:
      postgres:
        condition: service_healthy  # 👈 Wait for PostgreSQL to be ready
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      
    ports:
      - "8000:8000"
